install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop bucket add extras
  - ps: scoop install gcc universal-ctags

build_script: make
  
test_script: make test

artifacts:
  - name: cdecl.exe
    path: out/bin/release/cdecl.exe

deploy:
  provider: GitHub
  artifact: cdecl.exe
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
  on:
    APPVEYOR_REPO_TAG: true
  auth_token:
    secure: EjrQ/UksV/Z9ahXKENFr1gyGO778GPOyIRKvtRUZMWGxQ0SleqQDXMxfRjtqh9jd
