install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop bucket add extras
  - ps: scoop install gcc universal-ctags

build_script: 
  - make
  - ps: $hash = (get-filehash out/bin/release/cdecl.exe).hash
  - ps: echo "$hash *cdecl.exe" > out/bin/release/cdecl.exe.sha256
  
test_script: make test

artifacts:
  - name: cdecl.exe
    path: out/bin/release/cdecl.exe
  - name: cdecl.exe.sha256
    path: out/bin/release/cdecl.exe.sha256

deploy:
  provider: GitHub
  artifact: cdecl.exe, cdecl.exe.sha256
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
  on:
    APPVEYOR_REPO_TAG: true
  auth_token:
    secure: EjrQ/UksV/Z9ahXKENFr1gyGO778GPOyIRKvtRUZMWGxQ0SleqQDXMxfRjtqh9jd

after_deploy:
  - ps: |
      if (${env:APPVEYOR_REPO_TAG}) {
        $tag = ${env:APPVEYOR_REPO_TAG_NAME}
        $manifest = get-content cdecl.json | convertfrom-json
        $manifest.version = $tag.substring(1)
        $manifest.url = $manifest.url -replace replace "v([\d.])+", $tag
        $manifest.hash = $hash
        $manifest | convertto-json | set-content cdecl.json
        git add cdecl.json
        git commit -m "release($tag): update cdecl.json [skip ci]"
        git push
      }
      
skip_commits:
  message: /^chore/